import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const app=read('js/app.js'),index=read('index.html'),sw=read('sw.js'),migrations=read('js/migrations.js');
const actions=[...new Set([...app.matchAll(/data-action=["']([^"']+)["']/g)].map(m=>m[1]).filter(x=>!x.includes('${')))];
const handlerBlock=app.slice(app.indexOf('function handleAction('),app.indexOf('function go(p)',app.indexOf('function handleAction(')));
const handlers=new Set([...handlerBlock.matchAll(/['"]([^'"]+)['"]\s*:/g)].map(m=>m[1]));
const missing=actions.filter(a=>!handlers.has(a));
assert.deepEqual(missing,[],`Missing action handlers: ${missing.join(', ')}`);
const imports=[...app.matchAll(/from\s+['"](\.\/[^'"]+)['"]/g)].map(m=>m[1]);
for(const rel of imports) assert.ok(fs.existsSync(path.join(root,'js',rel.replace('./',''))),`App import exists: ${rel}`);
const assetBlock=sw.slice(sw.indexOf('const ASSETS'),sw.indexOf('];',sw.indexOf('const ASSETS'))+2);
const assets=[...assetBlock.matchAll(/['"](\.\/?[^'"]*)['"]/g)].map(m=>m[1]).filter(x=>x!=='./');
for(const rel of assets) assert.ok(fs.existsSync(path.join(root,rel.replace(/^\.\//,''))),`Cached asset exists: ${rel}`);
assert.ok(sw.includes("afloat-v1.9.0"),'service worker cache version');
assert.ok(index.includes("APP_VERSION='1.9.0'"),'standalone bundle version');
assert.ok(/CURRENT_SCHEMA\s*=\s*16/.test(migrations),'schema version 16');
console.log(`AFLOAT v1.9.0 integrity checks passed: ${actions.length} UI actions, ${assets.length} cached references.`);
